title: Türkiye Fenomenoloji Topluluğu
email: info@fenomenoloji.org.tr
description: Türkiye’de Fenomenoloji ve Fenomenolojinin Geleceği
url: "https://fenomenoloji.org.tr"
twitter_username: TrFenomenoloji
